Feature/185 Add no-image fallback for e-picture
valantic/vue-template pull request #281
Opened 2023-02-01 15:21 UTC by BeneRichi

## Pull request
Set the default value for the fallback property and make it optional - implement error handling for the img tag - store the srcset in data to be replaced with the fallback source in case the image resource specified in the srcset path is not found on the server - created picture route and page to test the component.
 
### Ticket
[185](https://github.com/valantic/vue-template/projects/1#card-87657797)
 
### Browser testing
http://localhost:9090/styleguide/sandbox/image
 
### Checklist
- [x] I merged the current development branch (before testing)
- [ ] Added JSDoc and styleguide demo
- [x] Tested all links in project relevant browsers
- [x] Tested all links in different screen sizes
- [ ] Did run automated tests and linters
- [x] Did assign ticket
- [x] Double checked target branch
 
## Review/Test checklist
- [ ] Did review code and documentation
- [ ] Tested all links in project relevant browsers
- [ ] Tested all links in different screen sizes
- [ ] Did check accessibility (Wave, only errors)
- [ ] Re-assign ticket to developer

2023-02-03 11:00 UTC, BeneRichi commented
@patric-eberle Can I merge this feature into Vue 2 now that we have looked at it together on Huddle?

2023-02-03 15:59 UTC, patric-eberle requested changes
Browser review looks good.

I changed the mapping of the `mappedSizes` computed, because it created an invalid string (starting with `,`) if no sizes have been given.

2023-02-03 15:59 UTC, patric-eberle commented on src/elements/e-picture.vue
> +
todo: please remove empty line.

2023-02-03 15:59 UTC, patric-eberle commented on src/elements/e-picture.vue
> +        src: this.srcset,
todo: please use `internalSrcSet` as key name, since `src` is also an `img` related attribute.

2023-02-03 15:59 UTC, patric-eberle commented on src/elements/e-picture.vue
> +      handleError() {
todo: please prefix event handlers with `on` according to the HTML naming of e.g. `onclick=""`.

```suggestion
      onError() {
```

2023-02-03 15:59 UTC, patric-eberle commented on src/styleguide/routes/picture.vue
> +               :sizes="sizes"
todo: please ALWAYS define dynamic props before static ones.

2023-02-03 15:59 UTC, patric-eberle commented on src/styleguide/routes/picture.vue
> +  import LDefault from '../../layouts/l-default.vue';
todo: please use `camelCase` and update usage.

```suggestion
  import lDefault from '../../layouts/l-default.vue';
```

2023-02-03 15:59 UTC, patric-eberle commented on src/styleguide/routes/picture.vue
> +          '(min-width: 600px)': 600,
todo: this syntax is invalid. The key should be a `number` or viewport size (e.g. `xs`). Format is `[viewport]: [maxDisplayWidthOfImage]. See e-picture.md for valid demos.

2023-02-06 14:56 UTC, BeneRichi commented
@MB-web @patric-eberle Ready for review

2023-02-07 10:40 UTC, patric-eberle approved these changes
Browser review is OK (except for the introduced, invalid attribute).

Please see my comment. You can merge yourself after the fix.

To get familiar with the options of responsive images, this article might be helpful: https://css-tricks.com/a-guide-to-the-responsive-images-syntax-in-html/

2023-02-08 07:30 UTC, BeneRichi commented on src/elements/e-picture.vue
> +         :internalSrcSet="fallback"
@patric-eberle You are completely.

2023-02-08 07:38 UTC, merged