#322 e-table enhancements
valantic/vue-template pull request #360
Opened 2024-01-19 10:01 UTC by patric-eberle

## Pull request
This PR applies some small improvements to the e-table component based on the changes from SF. I decided to not make a 1:1 copy, because some changes from that project seem to be too specific.
 
### Ticket
#322 
 
### Browser testing
- http://localhost:5173/styleguide/components/table
 
### Checklist
- [x] I merged the current development branch (before testing)
- [x] Added JSDoc and styleguide demo
- [x] Tested all links in project relevant browsers
- [x] Tested all links in different screen sizes
- [x] Did run automated tests and linters
- [x] Did assign ticket
- [x] Double checked target branch
 
## Review/Test checklist
- [ ] Did review code and documentation
- [ ] Tested all links in project relevant browsers
- [ ] Tested all links in different screen sizes
- [ ] Did check accessibility (Wave, only errors)
- [ ] Re-assign ticket to developer

2024-01-24 07:25 UTC, patric-eberle commented
@MB-web would be nice if you could also check this PR.

2024-01-29 13:24 UTC, mob8607 approved these changes

2024-01-29 13:26 UTC, mob8607 requested changes
Code looks good 👍 

Browser Review:

In Safari there seems to be a styling issue. There is an additional borders in each row:
<img width="1709" alt="Bildschirmfoto 2024-01-29 um 14 25 45" src="https://github.com/valantic/vue-template/assets/1636945/ff402892-226a-43f0-bcf1-dbaf8f210d69">

2024-04-17 09:12 UTC, mob8607 approved these changes

2024-04-17 09:12 UTC, merged